server:
  port: 8080
spring:
  application:
    name: myspringboot
  datasource:
    url: jdbc:mysql://localhost:3306/mysql?useUnicode=true&characterEncoding=utf-8&zeroDateTimeBehavior=convertToNull
    username: root
    password: 123456
    driver-class-name: com.mysql.cj.jdbc.Driver
mybatis:
  configuration:
    map-underscore-to-camel-case: true
  mapper-locations: "classpath:/mappers/*.xml"
  type-aliases-package: com.crazy.myspringboot.entity


